controllers/ApplicationController.php
<?php

namespace app\controllers;

use app\models\Catalog;
use app\models\User;
use Yii;
use app\models\Applications;
use app\models\search\ApplicationsSearch;
use yii\db\Exception;
use yii\db\Expression;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Writer\WriterFactory;
use Box\Spout\Common\Type;

/**
 * ApplicationController implements the CRUD actions for Applications model.
 */
class ApplicationController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin', 'head', 'manager']
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Applications models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ApplicationsSearch();

        /* По умолчанию - за сегодня */
        if(!Yii::$app->request->queryParams) {
            $searchModel->date_created = date('Y-m-d');
        }
        /* Если начальник */
        if(Yii::$app->user->can('head')) {
            $searchModel->region_id = Yii::$app->user->identity->region_id;
        }
        /* Если менеджер */
        if(Yii::$app->user->can('manager')) {
            $searchModel->author_id = Yii::$app->user->id;
        }


        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionAll()
    {
        $searchModel = new ApplicationsSearch();
        $subjects = [];

        /* Эта хрень нужна, потому что глючит фильтр заявок */
        if (!Yii::$app->request->queryParams) {
            $searchModel->date_start = Yii::$app->db->createCommand("SELECT MIN(date_created) FROM applications")->queryScalar();
            $searchModel->date_end = Yii::$app->db->createCommand("SELECT MAX(date_created) FROM applications")->queryScalar();
        }

        /* Если начальник - все заявки региона */
        if(Yii::$app->user->can('head')) {
            $searchModel->region_id = Yii::$app->user->identity->region_id;
        }
        /* Если менеджер - только его заявки */
        if(Yii::$app->user->can('manager')) {
            $searchModel->author_id = Yii::$app->user->id;
        }

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'regions' => Yii::$app->user->identity->getAllowedRegionsList(),
            'subjects' => Yii::$app->user->identity->getAllowedSubjectList(),
            'products' => Catalog::find()->where(['=', 'name', Catalog::NAME_PRODUCTS])->select('value')->indexBy('id')->column(),
            'currency' => Catalog::find()->where(['=', 'name', Catalog::NAME_CURRENCY])->select('value')->indexBy('id')->column(),
        ]);
    }

    /* т.к. табельный номер добавлен чуть позже, его нет в JSON массиве
        его нужно добавить этоим экшеном. В будущем пригодится для обновления
        табельных номеров
     */
    public function actionFixTableNumber() {
        while($models = Applications::find()->where(['IS', new Expression("other ->> 'authorTabel'"), NULL])->limit(200)->all()) {
            foreach ($models as $model) {
                $other = $model->other;
                $other['authorTabel'] = $model->author->tabel_number;
                $model->other = $other;
                $model->save();
            }
            $models = NULL;
        }
        return $this->redirect(['/application']);
    }

    public function actionExportAnswers() {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $state = Yii::$app->request->post('state');
        parse_str($state['json'], $model_data) ;

        $increment = $state['increment'];
        $increment_by = $state['increment_value'];

        $searchModel = new ApplicationsSearch($model_data['ApplicationsSearch']);
        if(
            preg_match('/\d{2}\.\d{2}\.\d{4} - \d{2}\.\d{2}\.\d{4}/', $searchModel->date_created)
            || preg_match('/\d{4}-\d{2}-\d{2} - \d{4}-\d{2}-\d{2}/', $searchModel->date_created)
        ) {
            $searchModel->date_start = substr($searchModel->date_created, 0, 10);
            $searchModel->date_start = (new \DateTime($searchModel->date_start))->format('Y-m-d');
            $searchModel->date_end = substr($searchModel->date_created, 13, 10);
            $searchModel->date_end = (new \DateTime($searchModel->date_end))->format('Y-m-d');
        }
        if(
            preg_match('/\d{2}\.\d{2}\.\d{4} \d{2}:\d{2}:\d{2} - \d{2}\.\d{2}\.\d{4} \d{2}:\d{2}:\d{2}/', $searchModel->date_created)
            || preg_match('/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} - \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/', $searchModel->date_created)
        ) {
            $searchModel->date_start = substr($searchModel->date_created, 0, 10);
            $searchModel->date_start = (new \DateTime($searchModel->date_start))->format('Y-m-d');
            $searchModel->date_end = substr($searchModel->date_created, 23, 10);
            $searchModel->date_end = (new \DateTime($searchModel->date_end))->format('Y-m-d');
        }

        $dataProvider = $searchModel->search($model_data);


        if( !$state['filename'] ) {
            $file_hash = Yii::$app->security->generateRandomString(8) . ".xlsx";
            $download = \yii\helpers\Url::to(["/reports/" . $file_hash]);
            $filename = Yii::getAlias("@webroot") . '/reports/' . $file_hash;
        } else {
            $download = $state['download'];
            $filename = $state['filename'];
        }

        $total = $dataProvider->getTotalCount();
        $items = $dataProvider->query
            ->select( new Expression("id, other ->> 'author' as Автор, other ->> 'authorTabel' as ТабельныйНомер , other ->> 'authorLogin' as Логин, CONCAT(other->>'region', '/', other->>'subject') as Регион, other ->> 'product' as Продукт, date_created, client_name, client_iin, value, sum, other ->>'currency' as Валюта, commend") )
            ->orderBy('id')->offset($increment)->limit($increment_by);

        $sql = $dataProvider->query->createCommand()->rawSql;
        $items = Yii::$app->db->createCommand($sql)->queryAll();

//        var_dump($items); exit;

        $headers = [
            'ID в базе',
            'ФИО менеджера', 'таб.номер менеджера', 'Логин', 'Регион/Подразделение', 'Продукт',
            'Дата привлечения', 'ФИО клиента', 'ИИН клиента', 'Количество привлеченного продукта',
            'Сумма привлеченного продукта', 'Валюта привлеченного продукта', 'Комментарий'
        ];

        try {
            /* Если файл существует */
            if (file_exists($filename)) {
                $reader = ReaderFactory::create(Type::XLSX);
                $reader->open($filename);

                $tempname = Yii::getAlias("@webroot") . "/reports/" . Yii::$app->security->generateRandomString(8) . ".xlsx";

                $writer = WriterFactory::create(Type::XLSX);
                $writer->openToFile($tempname);

                foreach ($reader->getSheetIterator() as $sheetIndex => $sheet) {
                    foreach ($sheet->getRowIterator() as $row) {
                        $writer->addRow($row);
                    }
                }

                foreach ($items as $poll) {
                    $writer->addRow($poll);
                }

                $reader->close();
                $writer->close();

                unlink($filename);
                rename($tempname, $filename);
            }
            /* Если файл не существует */
            else {
                $row_headers = $headers;
                $writer = WriterFactory::create(Type::XLSX);
                $writer->openToFile($filename);
                /* Записать табельный номер, если существует */
                $writer->addRow(['Табельный номер: ', Yii::$app->user->identity->tabel_number]);
                $writer->addRow($row_headers);
                foreach ($items as $poll) {
                    $writer->addRow($poll);
                }
                $writer->close();
            }
        } catch (\Exception $e) {
            var_dump($e->getMessage(), $filename);
        }

        $state['increment'] = $increment + $increment_by;
        $state['filename'] = $filename;
        $state['download'] = $download;
        $state['is_processed'] = sizeof($items) > 0;
        $state['total'] = $total;

        return $state;
    }

    /**
     * Displays a single Applications model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Applications model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Applications();
        $model->date_created = date('Y-m-d H:i:s');

//        echo "<pre>"; var_dump(Catalog::getRegionSubjects()[Yii::$app->user->identity->region_id]); exit;

        $managers = User::find()->where(['status' => User::STATUS_ACTIVE])->select('name')->indexBy('id')->column();

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\AuthItem;
use app\models\Catalog;
use app\models\UpdateUserForm;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login'],
                        'allow' => true
                    ],
                    [
                        'actions' => ['index', 'profile', 'logout'],
                        'allow' => true,
                        'roles' => ['admin', 'head', 'manager']
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionProfile() {

        $model = User::findOne(['id' => Yii::$app->user->id]);
        $model->role = $model->getRoleByName();
        $update_model = new UpdateUserForm();
        $update_model->scenario = UpdateUserForm::SCENARIO_UPDATE_INFO;
        $update_model->id = $model->id;
        $update_model->name = $model->name;
        $update_model->tabel_number = $model->tabel_number;
        $update_model->username = $model->username;
        $update_model->email = $model->email;
        $update_model->role = $model->role;
        $update_model->status = $model->status;
        $update_model->region_id = $model->region_id;
        $update_model->subject_id = $model->subject_id;

        if ($update_model->load(Yii::$app->request->post()) && $update_model->validate()) {

            $model->username = $update_model->username;
            $model->name = $update_model->name;
            $model->tabel_number = $update_model->tabel_number;
            $model->email = $update_model->email;
            $model->status = $update_model->status;
            $model->region_id = $update_model->region_id;
            $model->subject_id = $update_model->subject_id;
            $model->setRoleByName($update_model->role);
            if($model->save()) {
                Yii::$app->session->setFlash('success', 'Данные сохранены');
                return $this->refresh();
            } else {
                Yii::$app->session->setFlash('error', 'Ошибка сохранения');
                Logger::add(['message' => 'Попытка обновить данные пользователя провалилась', 'errors' => $model->errors, 'model' => $model], 'User');
            }
        }

        $auth_items = AuthItem::find()->select('description')->indexBy('name')->column();
        $statuses = User::getStatuses();
        $region_subjects = Catalog::getRegionSubjects();

        return $this->render('@app/modules/admin/views/user/update', [
            'model' => $update_model,
            'auth_items' => $auth_items,
            'statuses' => $statuses,
            'region_subjects' => $region_subjects,
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; <?=date('Y')?> <a href="https://smartlab.technology/">Smartlab.Technology</a>.</strong>
</footer>

views/layouts/header.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">APP</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">


                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="hidden-xs"><?=(Yii::$app->user->identity && Yii::$app->user->identity->email) ? Yii::$app->user->identity->email : 'x'?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-footer">
                            <div class="pull-right">
                                <?= Html::a(
                                    'Выход',
                                    ['/site/logout'],
                                    ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                ) ?>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

views/layouts/left.php
<?php
    use \yii\helpers\Url;
?>

<aside class="main-sidebar">

    <section class="sidebar">

        <?php if (Yii::$app->user->can('admin')): ?>
            <?= dmstr\widgets\Menu::widget(
                [
                    'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                    'items' => [
                        ['label' => 'Меню', 'options' => ['class' => 'header']],
                        ['label' => Yii::$app->user->identity->role, 'options' => ['class' => 'header']],
                        ['label' => 'Профиль', 'icon' => 'user', 'url' => Url::to(['/site/profile']) ],
                        ['label' => 'Заявки', 'icon' => 'user', 'url' => Url::to(['/application']) ],
                        ['label' => 'Все заявки', 'icon' => 'user', 'url' => Url::to(['/application/all']) ],
                        ['label' => 'Пользователи', 'icon' => 'user', 'url' => Url::to(['/admin/user']) ],
                        ['label' => 'Справочник', 'icon' => '', 'url' => Url::to(['/admin/catalog']) ],
                        ['label' => 'Вход', 'url' => ['/site/login'], 'visible' => Yii::$app->user->isGuest],
                    ],
                ]
            ) ?>
        <?php endif; ?>

        <?php if (Yii::$app->user->can('manager')): ?>
            <?= dmstr\widgets\Menu::widget(
                [
                    'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                    'items' => [
                        ['label' => 'Меню', 'options' => ['class' => 'header']],
                        ['label' => Yii::$app->user->identity->role, 'options' => ['class' => 'header']],
                        ['label' => 'Профиль', 'icon' => 'user', 'url' => Url::to(['/site/profile']) ],
                        ['label' => 'Заявки', 'url' => Url::to(['/application']) ],
                        ['label' => 'Все заявки', 'url' => Url::to(['/application/all']) ],
                        ['label' => 'Вход', 'url' => ['/site/login'], 'visible' => Yii::$app->user->isGuest],
                    ],
                ]
            ) ?>
        <?php endif; ?>

        <?php if (Yii::$app->user->can('head')): ?>
            <?= dmstr\widgets\Menu::widget(
                [
                    'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                    'items' => [
                        ['label' => 'Меню', 'options' => ['class' => 'header']],
                        ['label' => Yii::$app->user->identity->role, 'options' => ['class' => 'header']],
                        ['label' => 'Профиль', 'icon' => 'user', 'url' => Url::to(['/site/profile']) ],
                        ['label' => 'Заявки', 'url' => Url::to(['/application']) ],
                        ['label' => 'Все заявки', 'url' => Url::to(['/application/all']) ],
                        ['label' => 'Вход', 'url' => ['/site/login'], 'visible' => Yii::$app->user->isGuest],
                    ],
                ]
            ) ?>
        <?php endif; ?>

    </section>

</aside>

views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

if (Yii::$app->controller->action->id === 'login') {
/**
 * Do not use this code in your template. Remove it.
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'left.php',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>

views/layouts/user-layout.php
<?php

use app\assets\AppAsset;
use dmstr\web\AdminLteAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login') {
    /**
     * Do not use this code in your template. Remove it.
     * Instead, use the code  $this->layout = '//main-login'; in your controller.
     */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">


        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>