models/Applications.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "applications".
 *
 * @property int $id
 * @property string|null $date_created
 * @property int $region_id
 * @property int $subject_id
 * @property int $product_id
 * @property int $currency_id
 * @property int $author_id
 * @property int $client_iin
 * @property string $client_name
 * @property int|null $value
 * @property int|null $sum
 * @property string|null $commend
 * @property string|null $other
 *
 * @property Catalog $region
 * @property Catalog $subject
 * @property Catalog $product
 * @property Catalog $currency
 * @property User $author
 */
class Applications extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'applications';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date_created', 'other'], 'safe'],
            [['region_id', 'subject_id', 'product_id', 'currency_id', 'author_id', 'client_iin', 'client_name'], 'required'],
            [['region_id', 'subject_id', 'product_id', 'currency_id', 'author_id', 'client_iin', 'value', 'sum'], 'default', 'value' => null],
            [['region_id', 'subject_id', 'product_id', 'currency_id', 'author_id', 'client_iin', 'value', 'sum'], 'integer'],
            [['commend'], 'string'],
            [['client_name'], 'string', 'max' => 256],
            [['client_iin'], 'match', 'pattern' => '/^[0-9]{12}/'],
            [['region_id'], 'exist', 'skipOnError' => true, 'targetClass' => Catalog::className(), 'targetAttribute' => ['region_id' => 'id']],
            [['subject_id'], 'exist', 'skipOnError' => true, 'targetClass' => Catalog::className(), 'targetAttribute' => ['subject_id' => 'id']],
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => Catalog::className(), 'targetAttribute' => ['product_id' => 'id']],
            [['currency_id'], 'exist', 'skipOnError' => true, 'targetClass' => Catalog::className(), 'targetAttribute' => ['currency_id' => 'id']],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['author_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date_created' => 'Дата',
            'region_id' => 'Регион',
            'subject_id' => 'Подразделение',
            'product_id' => 'Продукт',
            'currency_id' => 'Валюта',
            'author_id' => 'Менеджер',
            'author_name' => 'Менеджер',
            'client_iin' => 'ИИН',
            'client_name' => 'Ф.И.О.',
            'value' => 'Количество',
            'sum' => 'Сумма',
            'commend' => 'Коментарий',
            'other' => 'Other',
        ];
    }

    /**
     * Gets query for [[Region]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRegion()
    {
        return $this->hasOne(Catalog::className(), ['id' => 'region_id']);
    }

    /**
     * Gets query for [[Subject]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSubject()
    {
        return $this->hasOne(Catalog::className(), ['id' => 'subject_id']);
    }

    /**
     * Gets query for [[Product]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(Catalog::className(), ['id' => 'product_id']);
    }

    /**
     * Gets query for [[Currency]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCurrency()
    {
        return $this->hasOne(Catalog::className(), ['id' => 'currency_id']);
    }

    /**
     * Gets query for [[Author]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'author_id']);
    }

    public function beforeSave($insert)
    {
        $this->other = [
            'product' => $this->product->value,
            'currency' => $this->currency->value,
            'author' => $this->author->name,
            'authorLogin' => $this->author->username,
            'authorTabel' => $this->author->tabel_number,
            'region' => $this->region->value,
            'subject' => $this->subject->value,
        ];
        return parent::beforeSave($insert);
    }

}

controllers/ApplicationController.php
<?php

namespace app\controllers;

use app\models\Catalog;
use app\models\User;
use Yii;
use app\models\Applications;
use app\models\search\ApplicationsSearch;
use yii\db\Exception;
use yii\db\Expression;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Writer\WriterFactory;
use Box\Spout\Common\Type;

/**
 * ApplicationController implements the CRUD actions for Applications model.
 */
class ApplicationController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin', 'head', 'manager']
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Applications models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ApplicationsSearch();

        /* По умолчанию - за сегодня */
        if(!Yii::$app->request->queryParams) {
            $searchModel->date_created = date('Y-m-d');
        }
        /* Если начальник */
        if(Yii::$app->user->can('head')) {
            $searchModel->region_id = Yii::$app->user->identity->region_id;
        }
        /* Если менеджер */
        if(Yii::$app->user->can('manager')) {
            $searchModel->author_id = Yii::$app->user->id;
        }


        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionAll()
    {
        $searchModel = new ApplicationsSearch();
        $subjects = [];

        /* Эта хрень нужна, потому что глючит фильтр заявок */
        if (!Yii::$app->request->queryParams) {
            $searchModel->date_start = Yii::$app->db->createCommand("SELECT MIN(date_created) FROM applications")->queryScalar();
            $searchModel->date_end = Yii::$app->db->createCommand("SELECT MAX(date_created) FROM applications")->queryScalar();
        }

        /* Если начальник - все заявки региона */
        if(Yii::$app->user->can('head')) {
            $searchModel->region_id = Yii::$app->user->identity->region_id;
        }
        /* Если менеджер - только его заявки */
        if(Yii::$app->user->can('manager')) {
            $searchModel->author_id = Yii::$app->user->id;
        }

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'regions' => Yii::$app->user->identity->getAllowedRegionsList(),
            'subjects' => Yii::$app->user->identity->getAllowedSubjectList(),
            'products' => Catalog::find()->where(['=', 'name', Catalog::NAME_PRODUCTS])->select('value')->indexBy('id')->column(),
            'currency' => Catalog::find()->where(['=', 'name', Catalog::NAME_CURRENCY])->select('value')->indexBy('id')->column(),
        ]);
    }

    /* т.к. табельный номер добавлен чуть позже, его нет в JSON массиве
        его нужно добавить этоим экшеном. В будущем пригодится для обновления
        табельных номеров
     */
    public function actionFixTableNumber() {
        while($models = Applications::find()->where(['IS', new Expression("other ->> 'authorTabel'"), NULL])->limit(200)->all()) {
            foreach ($models as $model) {
                $other = $model->other;
                $other['authorTabel'] = $model->author->tabel_number;
                $model->other = $other;
                $model->save();
            }
            $models = NULL;
        }
        return $this->redirect(['/application']);
    }

    public function actionExportAnswers() {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $state = Yii::$app->request->post('state');
        parse_str($state['json'], $model_data) ;

        $increment = $state['increment'];
        $increment_by = $state['increment_value'];

        $searchModel = new ApplicationsSearch($model_data['ApplicationsSearch']);
        if(
            preg_match('/\d{2}\.\d{2}\.\d{4} - \d{2}\.\d{2}\.\d{4}/', $searchModel->date_created)
            || preg_match('/\d{4}-\d{2}-\d{2} - \d{4}-\d{2}-\d{2}/', $searchModel->date_created)
        ) {
            $searchModel->date_start = substr($searchModel->date_created, 0, 10);
            $searchModel->date_start = (new \DateTime($searchModel->date_start))->format('Y-m-d');
            $searchModel->date_end = substr($searchModel->date_created, 13, 10);
            $searchModel->date_end = (new \DateTime($searchModel->date_end))->format('Y-m-d');
        }
        if(
            preg_match('/\d{2}\.\d{2}\.\d{4} \d{2}:\d{2}:\d{2} - \d{2}\.\d{2}\.\d{4} \d{2}:\d{2}:\d{2}/', $searchModel->date_created)
            || preg_match('/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} - \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/', $searchModel->date_created)
        ) {
            $searchModel->date_start = substr($searchModel->date_created, 0, 10);
            $searchModel->date_start = (new \DateTime($searchModel->date_start))->format('Y-m-d');
            $searchModel->date_end = substr($searchModel->date_created, 23, 10);
            $searchModel->date_end = (new \DateTime($searchModel->date_end))->format('Y-m-d');
        }

        $dataProvider = $searchModel->search($model_data);


        if( !$state['filename'] ) {
            $file_hash = Yii::$app->security->generateRandomString(8) . ".xlsx";
            $download = \yii\helpers\Url::to(["/reports/" . $file_hash]);
            $filename = Yii::getAlias("@webroot") . '/reports/' . $file_hash;
        } else {
            $download = $state['download'];
            $filename = $state['filename'];
        }

        $total = $dataProvider->getTotalCount();
        $items = $dataProvider->query
            ->select( new Expression("id, other ->> 'author' as Автор, other ->> 'authorTabel' as ТабельныйНомер , other ->> 'authorLogin' as Логин, CONCAT(other->>'region', '/', other->>'subject') as Регион, other ->> 'product' as Продукт, date_created, client_name, client_iin, value, sum, other ->>'currency' as Валюта, commend") )
            ->orderBy('id')->offset($increment)->limit($increment_by);

        $sql = $dataProvider->query->createCommand()->rawSql;
        $items = Yii::$app->db->createCommand($sql)->queryAll();

//        var_dump($items); exit;

        $headers = [
            'ID в базе',
            'ФИО менеджера', 'таб.номер менеджера', 'Логин', 'Регион/Подразделение', 'Продукт',
            'Дата привлечения', 'ФИО клиента', 'ИИН клиента', 'Количество привлеченного продукта',
            'Сумма привлеченного продукта', 'Валюта привлеченного продукта', 'Комментарий'
        ];

        try {
            /* Если файл существует */
            if (file_exists($filename)) {
                $reader = ReaderFactory::create(Type::XLSX);
                $reader->open($filename);

                $tempname = Yii::getAlias("@webroot") . "/reports/" . Yii::$app->security->generateRandomString(8) . ".xlsx";

                $writer = WriterFactory::create(Type::XLSX);
                $writer->openToFile($tempname);

                foreach ($reader->getSheetIterator() as $sheetIndex => $sheet) {
                    foreach ($sheet->getRowIterator() as $row) {
                        $writer->addRow($row);
                    }
                }

                foreach ($items as $poll) {
                    $writer->addRow($poll);
                }

                $reader->close();
                $writer->close();

                unlink($filename);
                rename($tempname, $filename);
            }
            /* Если файл не существует */
            else {
                $row_headers = $headers;
                $writer = WriterFactory::create(Type::XLSX);
                $writer->openToFile($filename);
                /* Записать табельный номер, если существует */
                $writer->addRow(['Табельный номер: ', Yii::$app->user->identity->tabel_number]);
                $writer->addRow($row_headers);
                foreach ($items as $poll) {
                    $writer->addRow($poll);
                }
                $writer->close();
            }
        } catch (\Exception $e) {
            var_dump($e->getMessage(), $filename);
        }

        $state['increment'] = $increment + $increment_by;
        $state['filename'] = $filename;
        $state['download'] = $download;
        $state['is_processed'] = sizeof($items) > 0;
        $state['total'] = $total;

        return $state;
    }

    /**
     * Displays a single Applications model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Applications model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Applications();
        $model->date_created = date('Y-m-d H:i:s');

//        echo "<pre>"; var_dump(Catalog::getRegionSubjects()[Yii::$app->user->identity->region_id]); exit;

        $managers = User::find()->where(['status' => User::STATUS_ACTIVE])->select('name')->indexBy('id')->column();

views/application/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="applications-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-sm-6">

            <?= $form->field($model, 'date_created')->widget(\kartik\datetime\DateTimePicker::className(), [
                'model' => $model,
                'attribute' => 'date_created',
                'disabled' => true,
                'readonly' => true
            ]) ?>

            <?= $form->field($model, 'client_iin')->widget(\yii\widgets\MaskedInput::className(), [
                'model' => $model,
                'attribute' => 'client_iin',
                'mask' => '999999999999',
            ])->textInput() ?>

            <?= $form->field($model, 'client_name')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'product_id')->widget(\kartik\widgets\Select2::className(), [
                'data' => $products,
                'maintainOrder' => true,
                'options' => [
                    'placeholder' => 'Продукт'
                ]
            ]) ?>

            <?= $form->field($model, 'currency_id')->widget(\kartik\widgets\Select2::className(), [
                'data' => $currency,
                'maintainOrder' => true,
                'options' => [
                    'placeholder' => 'Валюта'
                ]
            ]) ?>

            <div class="row">
                <div class="col-xs-6">
                    <?= $form->field($model, 'value')->textInput(['type' => 'number']) ?>
                </div>
                <div class="col-xs-6">
                    <?= $form->field($model, 'sum')->textInput(['type' => 'number']) ?>
                </div>
            </div>
        </div>
        <div class="col-sm-6">

            <?= $form->field($model, 'author_id')->widget(\kartik\widgets\Select2::className(), [
                'data' => $managers,
                'maintainOrder' => true,
                'options' => [
                    'placeholder' => 'Регион',
                    'disabled' => !Yii::$app->user->can('admin')
                ]
            ]) ?>

            <?= $form->field($model, 'region_id')->widget(\kartik\widgets\Select2::className(), [
                'data' => $regions,
                'maintainOrder' => true,
                'options' => [
                    'placeholder' => 'Регион',
                    'disabled' => !Yii::$app->user->can('admin')
                ]
            ]) ?>

            <?= $form->field($model, 'subject_id')->widget(\kartik\widgets\Select2::className(), [
                'data' => $subjects,
                'maintainOrder' => true,
                'options' => [
                    'placeholder' => 'Подразделение',
                    'disabled' => !Yii::$app->user->can('admin') && !Yii::$app->user->can('head')
                ]
            ]) ?>

            <?= $form->field($model, 'commend')->textarea(['rows' => 6]) ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/application/_search.php
<?php

use kartik\daterange\DateRangePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\ApplicationsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="applications-search">

    <?php $form = ActiveForm::begin([
        'action' => [Yii::$app->controller->action->id],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?=$form->field($model, 'date_created')->widget(DateRangePicker::classname(), [
        'useWithAddon'=>false,
        'model'=>$model,
        'attribute'=>'date_created',
        'options' => [
            'placeholder' => Yii::t('app', 'Дата'),
            'class' => 'form-control',
        ],
        'startAttribute' => 'date_start',
        'endAttribute' => 'date_end',
        //'convertFormat'=>true,
        'presetDropdown'=>true,
        'pluginOptions' => [
            'alwaysShowCalendars' => true,
            'opens'=>'right',
            'locale' => [
                'format' => 'DD.MM.YYYY',
            ]
        ]
    ])->label(false);?>

    <?= $form->field($model, 'region_id') ?>

    <?= $form->field($model, 'subject_id') ?>

    <?= $form->field($model, 'product_id') ?>

    <?php // echo $form->field($model, 'currency_id') ?>

    <?php // echo $form->field($model, 'author_id') ?>

    <?php // echo $form->field($model, 'client_iin') ?>

    <?php // echo $form->field($model, 'client_name') ?>

    <?php // echo $form->field($model, 'value') ?>

    <?php // echo $form->field($model, 'sum') ?>

    <?php // echo $form->field($model, 'commend') ?>

    <?php // echo $form->field($model, 'other') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/application/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */

$this->title = 'Добавление новой заявки';
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="applications-create">

    <?= $this->render('_form', [
        'model' => $model,
        'regions' => $regions,
        'subjects' => $subjects,
        'products' => $products,
        'currency' => $currency,
        'managers' => $managers,
    ]) ?>

</div>

views/application/index.php
<?php

use app\assets\AppAsset;
use kartik\daterange\DateRangePicker;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\search\ApplicationsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Заявки';
$this->params['breadcrumbs'][] = $this->title;

$columns = [
    'id',
    [
        'attribute' => 'date_created',
        'filter' => Yii::$app->controller->action->id == 'all' ? DateRangePicker::widget([
            'useWithAddon'=>false,
            'model'=>$searchModel,
            'attribute'=>'date_created',
            'options' => [
                'placeholder' => Yii::t('app', 'Дата'),
                'class' => 'form-control',
            ],
            'startAttribute' => 'date_start',
            'endAttribute' => 'date_end',
            //'convertFormat'=>true,
            'presetDropdown'=>true,
            'pluginOptions' => [
                'alwaysShowCalendars' => true,
                'opens'=>'right',
                'locale' => [
                    'format' => 'YYYY-MM-DD',
                ]
            ]
        ]) : false,
    ],
    [
        'attribute' => 'region_id',
        'value' => function ($model) {
            return $model->other['region'];
        },
        'filter' => isset($regions) ? $regions : null
    ],
    [
        'attribute' => 'subject_id',
        'value' => function ($model) {
            return $model->other['subject'];
        },
        'filter' => isset($subjects) ? $subjects : null
    ],
    [
        'attribute' => 'product_id',
        'value' => function ($model) {
            return $model->other['product'];
        },
        'filter' => isset($products) ? $products : null
    ],
    [
        'attribute' => 'currency_id',
        'value' => function ($model) {
            return $model->other['currency'];
        },
        'filter' => isset($currency) ? $currency : null
    ],
    [
        'attribute' => 'author_name',
//                'label' => 'Менеджер',
        'value' => function ($model) {
            return $model->other['author'];
        }
    ],
    // TODO: Вынести это в отдельное поле
    [
        'attribute' => 'author_tabel_number',
        'label' => 'Табельный номер',
        'value' => function ($model) {
            return $model->author->tabel_number;
        }
    ],
    'client_iin',
    'client_name',
    [
        'attribute' => 'value',
        'filter' => false
    ],
    [
        'attribute' => 'sum',
        'filter' => false
    ],
    [
        'attribute' => 'commend',
        'filter' => false
    ],
    [
        'class' => 'yii\grid\ActionColumn',
        'template' => '{view}'
    ],
];

$extra_columns = [];
if(Yii::$app->user->can('admin')) {
    $extra_columns = [
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update}'
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{delete}'
        ],
    ];
}

$columns = array_merge($columns, $extra_columns);

?>

<?php
    $exportLink = \yii\helpers\Url::to(['/application/export-answers']);
    $this->registerJs("var exportLink = '{$exportLink}'", \yii\web\View::POS_HEAD);
    $this->registerJsFile( Yii::getAlias('@web/js/export-questions.js') , ['depends' => AppAsset::className()]);
?>

<div class="applications-index">


    <?php \yii\bootstrap\Modal::begin([
        'id' => 'export_answers',
        'header' => 'Выгрузить заявки в Excel',
        'clientOptions' => [
            'show' => false
        ]
    ]) ?>

    <div class="export-modal">

        <div class="query-status">
            <p id="status_row"> Нажмите кнопку, чтобы начать экспорт заявок. Дождитесь завершения формирования документа. </p>
            <iframe id="downloadFrame" style="display:none;"></iframe>
        </div>

        <div id="btns_container" class="btns">
            <button style="min-width: 190px" class="btn btn-success" id="start_export">Начать</button>
        </div>

    </div>

    <?php \yii\bootstrap\Modal::end() ?>

    <?php $form = ActiveForm::begin(['id' => 'polls_form', 'action' => \yii\helpers\Url::to(['/polls/default/export-list'])]); ?>
        <?= $form->field($searchModel, 'id')->hiddenInput()->label(false) ?>
        <?= $form->field($searchModel, 'date_created')->hiddenInput()->label(false) ?>
        <?= $form->field($searchModel, 'region_id')->hiddenInput()->label(false) ?>
        <?= $form->field($searchModel, 'subject_id')->hiddenInput()->label(false) ?>
        <?= $form->field($searchModel, 'product_id')->hiddenInput()->label(false) ?>
        <?= $form->field($searchModel, 'currency_id')->hiddenInput()->label(false) ?>
        <?= $form->field($searchModel, 'currency_id')->hiddenInput()->label(false) ?>
        <?= $form->field($searchModel, 'author_name')->hiddenInput()->label(false) ?>
    <?php ActiveForm::end(); ?>
    <p>
        <?= Html::a('Добавить', ['create'], ['class' => 'btn btn-success']) ?>
        <?php
            if (Yii::$app->user->can('admin') || Yii::$app->user->can('head')) {
                echo Html::button('Выгрузить заявки в Excel', ['class' => 'btn btn-success', 'onclick' => '$("#export_answers").modal("show")']);
            }
        ?>
    </p>

<!--    --><?php //echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => Yii::$app->controller->action->id === 'index' ? null : $searchModel,
        'columns' => $columns,
    ]); ?>

</div>

views/application/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */

$this->title = 'Редактирование заявки №' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => "№" . $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="applications-update">

    <?= $this->render('_form', [
        'model' => $model,
        'regions' => $regions,
        'subjects' => $subjects,
        'products' => $products,
        'currency' => $currency,
        'managers' => $managers,
    ]) ?>

</div>

views/application/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */

$this->title = "Заявка #" . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Все заявки', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="applications-view">

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'date_created',
            [
                'attribute' => 'region_id',
                'value' => function ($model) {
                    return $model->other['region'];
                }
            ],
            [
                'attribute' => 'subject_id',
                'value' => function ($model) {
                    return $model->other['subject'];
                }
            ],
            [
                'attribute' => 'product_id',
                'value' => function ($model) {
                    return $model->other['product'];
                }
            ],
            [
                'attribute' => 'currency_id',
                'value' => function ($model) {
                    return $model->other['currency'];
                }
            ],
            [
                'attribute' => 'author_name',
                'label' => 'Автор',
                'value' => function ($model) {
                    return $model->other['author'];
                }
            ],
            'client_iin',
            'client_name',
            'value',
            'sum',
            'commend:ntext',
        ],
    ]) ?>

</div>